/* Sabrina Ferreira Interiores — catálogo de projetos.
   Para publicar um projeto novo: crie assets/projetos/<slug>/ com cover.webp e
   as fotos numeradas (01.webp, 02.webp, ...), some uma entrada aqui e pronto. */
window.PROJETOS = [
  {
    slug: 'casacor-2025',
    nome: 'Janelas para o Mundo',
    cat: 'casacor',
    rotulo: 'CASACOR 2025',
    nota: 'CASACOR Santa Catarina, em parceria com a Dimas Construções',
    alt: 'Sala de jantar do ambiente Janelas para o Mundo, com mesa redonda, nichos iluminados e vista para o jardim',
    fotos: 21,
    largo: true,
  },
  {
    slug: 'loja-carlos',
    nome: 'Loja Carlos Pisos e Laminados',
    cat: 'comercial',
    rotulo: 'Comercial',
    nota: 'Showroom, escritórios e área de convivência',
    alt: 'Showroom da loja Carlos Pisos e Laminados, com bancada em madeira e parede verde',
    fotos: 20,
  },
  {
    slug: 'pousada-w32',
    nome: 'Pousada W32',
    cat: 'hotelaria',
    rotulo: 'Hotelaria',
    nota: 'Apartamentos, recepção e área de café da manhã',
    alt: 'Entrada da Pousada W32, com parede em pedra, escada e poltronas em tom terracota',
    fotos: 12,
  },
  {
    slug: 'casa-do-lago',
    nome: 'Casa do Lago',
    cat: 'residencial',
    rotulo: 'Residencial',
    nota: 'Delta Ville · interiores completos, do social às suítes',
    alt: 'Cozinha e sala de jantar integradas da Casa do Lago, com forro ripado em madeira',
    fotos: 12,
  },
  {
    slug: 'casa-origem',
    nome: 'Casa Origem',
    cat: 'residencial',
    rotulo: 'Residencial',
    nota: 'Delta Ville · living, terraço e espaço gourmet',
    alt: 'Terraço da Casa Origem, com pergolado metálico, banco corrido e lareira ecológica',
    fotos: 12,
  },
  {
    slug: 'casa-aura',
    nome: 'Casa Aura',
    cat: 'residencial',
    rotulo: 'Residencial',
    nota: 'Reserva da Pedra · social, suítes e área externa',
    alt: 'Fachada da Casa Aura vista da piscina, com varanda aberta para o living',
    fotos: 12,
  },
  {
    slug: 'cobertura-brisa',
    nome: 'Cobertura Brisa',
    cat: 'residencial',
    rotulo: 'Residencial',
    nota: 'Living, gourmet e varanda com vista para o mar',
    alt: 'Living da Cobertura Brisa integrado à varanda, com vista para o mar',
    fotos: 12,
    largo: true,
  },
  {
    slug: 'casa-elo',
    nome: 'Casa Elo',
    cat: 'residencial',
    rotulo: 'Residencial',
    nota: 'Reserva da Pedra · living, suíte master e terraço',
    alt: 'Hall da Casa Elo, com escada escultural, lareira e painel em madeira',
    fotos: 14,
  },
  {
    slug: 'casa-essenza',
    nome: 'Casa Essenza',
    cat: 'residencial',
    rotulo: 'Residencial',
    nota: 'Reserva da Pedra · interiores em pé-direito duplo',
    alt: 'Living da Casa Essenza em pé-direito duplo, com painel de pedra e marcenaria iluminada',
    fotos: 12,
  },
  {
    slug: 'suite-alva',
    nome: 'Suíte Alva',
    cat: 'residencial',
    rotulo: 'Residencial',
    nota: 'Reserva da Pedra · suíte e closet sob medida',
    alt: 'Suíte Alva, com cabeceira em mármore, iluminação embutida e paleta em tons de areia',
    fotos: 11,
  },
  {
    slug: 'casa-oliva',
    nome: 'Casa Oliva',
    cat: 'residencial',
    rotulo: 'Residencial',
    nota: 'Living, cozinha e suítes com décor clássico',
    alt: 'Living da Casa Oliva, com arco em verde-oliva, sofá claro e boiserie',
    fotos: 12,
  },
  {
    slug: 'woa-sky-towers',
    nome: 'WOA Sky Towers',
    cat: 'residencial',
    rotulo: 'Residencial',
    nota: 'Apartamento completo, do lavabo à suíte master',
    alt: 'Sala de jantar do apartamento WOA Sky Towers, com mesa redonda e parede em verde-oliva',
    fotos: 12,
  },
  {
    slug: 'apartamento-harmonia',
    nome: 'Apartamento Harmonia',
    cat: 'residencial',
    rotulo: 'Residencial',
    nota: 'Cidade Continente · social, cozinha e três suítes',
    alt: 'Living do Apartamento Harmonia, com sofá curvo, tapete claro e marcenaria em madeira escura',
    fotos: 13,
  },
];
